### ISSUE TITLE
Make activate link URL in email configurable

### ISSUE THREAD

**Issue by dambridge** [jacksleight/statamic-memberbox#27]
@jacksleight Thanks for being so responsive on other issues, truly appreciate it! I think I found a last mile that connects to #23 peripherally, but it's not a bug.

I see we can publish the lang file for the activation notice email which is awesome. In my case tho, I need to change the button link so I can put the URL in to my custom activation page instead of the 'out of the box' URL. Is this possible?

**Comment by jacksleight** [comment]
If you set the `statamic.memberbox.routes.activate` config that should be the link that appears in the activation email.

Or have I misunderstood?

**Comment by jacksleight** [comment]
Hey, guessing this worked OK so will close this now. 👍
