### ISSUE TITLE
Error when saving the user profile form 

### ISSUE THREAD

**Issue by mikemartin** [jacksleight/statamic-memberbox#30]
## Bug Description

Error thrown when user profile form is saved.

Target class [UsersController] does not exist on http://iveymbaa.test/!/statamic-memberbox/profile request

## Extra Detail
https://flareapp.io/share/17WO4E37

## Environment

Environment
Application Name: Statamic
Laravel Version: 10.10.1
PHP Version: 8.1.17
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: iveymbaa4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.9.0 PRO

Statamic Addons
jacksleight/statamic-memberbox: 2.0.0
statamic/migrator: dev-master

**Comment by jacksleight** [comment]
Whoops, thanks for the report.

This was due to a BC break in Statamic 4 I didn't spot when testing the new version. Fixed in 2.0.1.

FYI you only need the MB profile form if you need file upload support. If you're not you can use the core version.
