### ISSUE TITLE
Class "Str" not found in BaseTag.php

### ISSUE THREAD

**Issue by mikemartin** [jacksleight/statamic-memberbox#6]
Hey @jacksleight,

Wondeful addon! I'm just digging into it today and hit this error on the Change Password form. 
Should this line be `use Statamic\Support\Str;`?

https://github.com/jacksleight/statamic-memberbox/blob/e44717d827804902410f4b41beee3e110a7b498b/src/Tags/BaseTag.php#L7
 
**Support details**
Statamic 3.2.23 Pro
Laravel 8.73.1
PHP 7.4.25
doublethreedigital/duplicator 2.0.1
doublethreedigital/runway 1.1.0
goldnead/statamic-toc 1.0.9
jacksleight/statamic-memberbox 0.4.3
mikemartin/helpscout-beacon 1.0.2
mikemartin/samcart 1.0.8
statamic/seo-pro 2.3.2

**Comment by jacksleight** [comment]
Ah good spot, shouldn't have been using a class alias. Thanks for the report! Fixed in v0.4.4.
