### ISSUE TITLE
Member is created even if something goes wrong

### ISSUE THREAD

**Issue by rabol** [jacksleight/statamic-memberbox#9]
## Bug Description
I tried to create a new member, and when hitting the 'create and send email'.
I get the error 'Something went wrong'

## How to Reproduce
brand new installation
create a new member

## Environment

Statamic 3.3.11 Pro
Laravel 9.12.2
PHP 8.0.19
jacksleight/statamic-memberbox 0.5.1

**Comment by jacksleight** [comment]
Hey @rabol, thanks for the report.

Could I ask, does it work if you don't send the email, and do you get the same issue if you create a normal Statamic user and do "create and send email"? I'm wondering if the issue might be the mail configuration, as I've run into that in the past. The email is sent after the member is created, which would explain why the member is added despite the error.

**Comment by rabol** [comment]
Hi

Yes, I'm also sure that it's mail configuration :)

but... the error is 'Something went' wrong :)

I'll double check the mail settings and get back

**Comment by rabol** [comment]
yes, with proper email setup, no issues... so maybe a better error messages ?

**Comment by jacksleight** [comment]
Great, glad you got it working. Yeah I'll add a better message, I think "Something went wrong" is just Statamic's default for any uncaught error.
